### ISSUE TITLE
connect: support using a config file with connection details?

### ISSUE THREAD

**Issue by sckott** [ropensci/elastic#243]
related to #87 

I can see a use case for a config file with connection details for 1 or more elasticsearch instances, and then `connect()` pulls in that info. e.g., 

```r
connect(file = "es_setup.yml")
```

where

```yaml
host: some.ip.address
path: /search
transport_schema: https
user: foo
pwd: bar
errors: complete
```

or to support many, do 

```yaml
setup_one:
  host: some.ip.address
  path: /search
  transport_schema: https
  user: foo
  pwd: bar
  errors: complete
setup_two:
  host: some.other.ip.address
  path: /query
  transport_schema: http
  user: hello
  pwd: world
  errors: simple
```

and then call in the details you want like 

```r
connect(file = list(setup_two = "es_setup.yml"))
```

or some other thing, not sure 🤔
